// src/app/components/button/button.component.ts
import { Component, Input } from '@angular/core';
// @ts-ignore
import { colors } from 'custom_tokens/Colors';
// @ts-ignore
import { space } from 'custom_tokens/Space';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css']
})

export class ButtonComponent {
  @Input() color: string = colors.primary;
  @Input() paddingY: string = space.xs;
  @Input() paddingX: string = space.s;

  buttonText: string = 'Angular Button';
}

<!-- Componente estilizado diretamente e usando os tokens importados -->
<button
  style="background: {{ color }}; padding: {{ paddingY }} {{ paddingX }};"
>
  {{ buttonText }}
</button>

// react-app/src/components/Button/index.tsx
import React from "react";
// @ts-ignore
import { colors } from 'custom_tokens/Colors';
// @ts-ignore
import { space } from 'custom_tokens/Space';

import "./index.css";

console.log('space', space);

const Button = () => (
  <button
    className="reactButton"
    type="button"
    style={{
      background: colors.primary,
      padding: `${space.xs} ${space.s}`,
    }}
  >
    <span>React Button</span>
  </button>
);

export { Button }
